// careers.js

const careers = [
    "Software Development",
    "Graphic Design",
    "Marketing Strategy",
    "Data Analysis",
    "Environmental Science",
    "Human Resources",
    "Event Planning",
    "Cybersecurity",
    "Fashion Design",
    "Culinary Arts",
    "Video Production",
    "Financial Planning",
    "Health and Wellness Coaching",
    "Social Media Management",
    "Project Management",
    "Teaching and Education",
    "Nursing",
    "Counseling",
    "Aerospace Engineering",
    "Photography",
    "Public Relations",
    "User Experience (UX) Design",
    "Artificial Intelligence",
    "Fitness Training",
    "Business Analytics",
    "Content Writing",
    "Biomedical Research",
    "Sustainable Agriculture",
    "Interior Design",
    "Physical Therapy",
    "Renewable Energy",
    "Supply Chain Management",
    "Mobile App Development",
    "Market Research",
    "Animation",
    "Real Estate Development",
    "Event Photography",
    "Occupational Therapy",
    "Entrepreneurship",
    "Film Production",
    "Humanitarian Aid Work",
    "Bioinformatics",
    "User Interface (UI) Design",
    "Public Health",
    "Veterinary Medicine",
    "Financial Analysis",
    "Nonprofit Management",
    "Cryptocurrency Trading",
    "E-commerce Management",
    "Robotics Engineering",
    "Brand Management",
    "Geology",
    "Architecture",
    "Sports Coaching",
    "Political Campaign Management",
    "Forensic Science",
    "Digital Marketing",
    "Clinical Psychology",
    "Music Production",
    "Market Trend Analysis",
    "Marine Biology",
    "Product Management",
    "Social Work",
    "Virtual Reality Development",
    "Journalism",
    "Disaster Management",
    "Business Intelligence",
    "Medical Research",
    "Neurology",
    "Animation",
    "Chemical Engineering",
    "Sales Management",
    "Foreign Diplomacy",
    "Game Design",
    "Agricultural Management",
    "Public Policy Analysis",
    "Personal Training",
    "Mobile Marketing",
    "Aerospace Technology",
    "International Business",
    "Art Therapy",
    "Renewable Energy Policy",
    "UI/UX Research",
    "Veterinary Surgery",
    "Economic Development",
    "Content Strategy",
    "Artificial Neural Networks",
    "Human-Computer Interaction",
    "Music Therapy",
    "Sustainable Architecture",
    "Financial Planning",
    "Forensic Accounting",
    "Supply Chain Analytics",
    "Astrophysics",
    "Outdoor Adventure Leadership",
    "Creative Writing",
    "Immunology",
    "Political Journalism",
    "Diversity and Inclusion",
    "Geospatial Analysis",
    "Medical Illustration",
    "Social Entrepreneurship",
    "Nanotechnology",
    "Cryptography",
    "Sustainability Consulting",
    "Computer Hardware Engineering",
    "Archaeology",
    "Brand Strategy",
    "Biochemistry",
    "Clinical Nutrition",
    "Wildlife Conservation",
    "SEO (Search Engine Optimization)",
    "Educational Technology",
    "Youth Counseling",
    "Quantum Computing",
    "International Development",
    "Cultural Anthropology",
    "Gaming Journalism",
    "Environmental Engineering",
    "Space Exploration",
    "Mobile App Design",
    "Human Rights Advocacy",
    "Disaster Relief Coordination",
    "Sports Medicine",
    "Business Process Optimization",
    "Music Composition",
    "Sustainable Fashion",
    "Renewable Energy Engineering",
    "AI Ethics",
    "Environmental Policy",
    "Virtual Events Planning",
    "Quantum Physics",
    "Product Design",
    "Rehabilitation Counseling",
    "Green Building Design",
    "Technical Writing",
    "Occupational Health and Safety",
    "Refugee Advocacy",
    "Agricultural Economics",
    "Computational Linguistics",
    "Human-Centered Design",
    "International Relations",
    "Astrophotography",
    "Sustainable Tourism",
    "Social Impact Investing",
    "Mobile Game Development",
    "Animal Behavior",
    "Genetic Counseling",
    "Sustainable Business",
  ];
  
const careersObjects = careers.map(career => ({ value: career, label: career }));

export default careersObjects;
  